CREATE TABLE IF NOT EXISTS GymCheckIn(
  CheckInID SERIAL PRIMARY KEY,
  MemberID INT,
  CheckInTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CheckOuTime TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (MemberID) REFERENCES Members(memberID)
);

SELECT * FROM GymCheckIn