/* Queries */

--3.Calculate the total revenue generated by all orders.

SELECT
    SUM(p.price * od.quantity) AS total_revenue
FROM orderdetails AS od
INNER JOIN products AS p ON od.product_id = p.product_id;




-- Create a view to calculate total revenue
CREATE OR REPLACE VIEW Total_revenue AS
SELECT
    SUM(p.price * od.quantity) AS total_revenue
FROM orderdetails AS od
INNER JOIN products AS p ON od.product_id = p.product_id;


SELECT * FROM Total_revenue;
-- DROP VIEW total_revenue;